import{a as $,S as b,i as d}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function q(){const o=document.querySelector(".loader");o.style.display="none"}async function p(o){const a=`https://pixabay.com/api/?key=42578241-c2049137a4025890cf19aabd8&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;try{const n=await $.get(a);if(!n.data||!n.data.hits||n.data.hits.length===0)throw new Error("No images found");return n.data.hits}catch(n){throw q(),console.error(n.message),n}}function m(o){const r=document.querySelector(".gallery"),s=o.map(({webformatURL:i,largeImageURL:e,tags:t,likes:a,views:n,comments:S,downloads:L})=>`<li class="gallery-item">
                <a class="gallery-link" href="${e}">
                <img class="gallery-image"
                src="${i}"
                data-source="${e}"
                alt="${t}"/></a>
                <p><span class="image-items-text">Likes: </span>${a}</p>
                <p><span class="image-items-text">Views: </span>${n}</p>
                <p><span class="image-items-text">Comments: </span>${S}</p>
                <p><span class="image-items-text">Downloads: </span>${L}</p>
            </li>`).join("");r.insertAdjacentHTML("beforeend",s)}const w=document.querySelector("form"),A=document.querySelector(".search-btn"),y=document.querySelector(".gallery"),f=document.querySelector('input[type="text"]'),h=document.querySelector(".loader"),c=document.querySelector(".load-more-btn"),g=new b(".gallery a",{captionsData:"alt",captionDelay:250});function I(){h.style.display="block"}function l(){h.style.display="none"}function x(){y.innerHTML=""}async function O(o){o.preventDefault();const r=f.value.trim();x(),I(),w.reset();try{const s=await p(r);m(s),l(),g.refresh(),s.length>1&&(c.style.display="flex")}catch{l(),c.style.display="none",d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}}A.addEventListener("click",O);let u=1,v=15;const E=20,N=Math.ceil(100/E);c.addEventListener("click",async()=>{const o=f.value.trim();try{const r=await p(o,u,E,v);m(r),g.refresh(),u+1;const s=y.getBoundingClientRect().height;window.scrollBy({top:2*s,behavior:"smooth"}),r.length>N&&(c.style.display="none",d.info({title:"End of search results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){console.error(r.message)}});
//# sourceMappingURL=commonHelpers.js.map
